// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refreshTokens.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createToken = `-- name: CreateToken :one
INSERT INTO refresh_tokens (token, user_id,  expires_at)
VALUES (
    $1,
    $2,
    $3
)
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type CreateTokenParams struct {
	Token     string    `json:"token"`
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, createToken, arg.Token, arg.UserID, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getToken = `-- name: GetToken :one
SELECT token, created_at, updated_at, user_id, expires_at, revoked_at FROM refresh_tokens
WHERE token = $1
`

func (q *Queries) GetToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, getToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeToken = `-- name: RevokeToken :one
UPDATE refresh_tokens
SET revoked_at = $1, updated_at = now()
WHERE token = $2
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type RevokeTokenParams struct {
	RevokedAt sql.NullTime `json:"revoked_at"`
	Token     string       `json:"token"`
}

func (q *Queries) RevokeToken(ctx context.Context, arg RevokeTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, revokeToken, arg.RevokedAt, arg.Token)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const updateToken = `-- name: UpdateToken :one
UPDATE refresh_tokens
SET token = $1, expires_at = $2, updated_at = now()
WHERE token = $3
RETURNING token, created_at, updated_at, user_id, expires_at, revoked_at
`

type UpdateTokenParams struct {
	Token     string    `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	Token_2   string    `json:"token_2"`
}

func (q *Queries) UpdateToken(ctx context.Context, arg UpdateTokenParams) (RefreshToken, error) {
	row := q.db.QueryRowContext(ctx, updateToken, arg.Token, arg.ExpiresAt, arg.Token_2)
	var i RefreshToken
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}
